aptos-move/aptos-vm/src/block_executor/mod.rs
crates/aptos-metrics-core/src/const_metric.rs
package-lock.json
types/src/validator_signer.rs

Devnet merge

---

.vscode/settings.json

Let developers configure their VSCode without turning this into commit fests and battles of preferences.

chore: remove VSCode configuration from git

---

storage/schemadb/src/lib.rs

Use a rocksdb type that is not dependent on the features with which the crate is compiled, since some code in this crate uses API that's specific to a particular target type of the DB alias.
Should unbreak the build in https://github.com/movementlabsxyz/movement/pull/34

schemadb: Remove API variability

---

storage/aptosdb/src/db/aptosdb_test.rs
storage/aptosdb/src/db/include/aptosdb_writer.rs
storage/storage-interface/src/lib.rs

We need the up-to-version ledger info when reverting the database to a past commit,
all other information needed for reversion can be obtained either from this data structure
or from the database itself.
Existing tests pass after modifications.

Make `LedgerInfo` the source of truth on revert

---

crates/aptos/CHANGELOG.md
crates/aptos/README.md
crates/aptos/homebrew/README.md
crates/aptos/src/account/list.rs
crates/aptos/src/update/tool.rs

Some cosmetic fixes to brand Aptos CLI as Movement CLI.
- [ x ] Documentation update
- [x ] Aptos CLI/SDK
Visual review
One thing I'm unsure about is how to add Movement Labs copyright? 
For example the top of a file has
```python
```
I could add the Movement Labs copyright above it, like this:
```python
```
Does that seem like a good way to do it?
- [x ] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x ] I identified and added all stakeholders and component owners affected by this change as reviewers
- [x ] I have made corresponding changes to the documentation

Cosmetic fixes to brand the CLI as Movement CLI

---

aptos-move/vm-genesis/Cargo.toml
aptos-move/vm-genesis/src/lib.rs

Re-fix the zero divide (once done in #24 for the `suzuka` branch) on calculating the rewards rate on top of the recently synced Movement trunk.

fix(vm-genesis): fix zero division, use the zero rewards rate instead

---

crates/aptos/src/common/init.rs
crates/aptos/src/common/utils.rs

CLI link fixes; needs review and final explorer links from @0xPrimata 
Also removed mainnet as a network option.
- [ x] New feature
- [ x] Bug fix
- [ x] Performance improvement
- [ x ] Movement CLI/SDK
I tested manually; explorer links are not finalized so this needs the final explorer links for Movement devnet and testnet.
Be sure that the RPC and faucet links are correct and that the way I commented out mainnet for now is acceptable.
- [ x ] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [ x ] I have performed a self-review of my own code
- [ x ] I identified and added all stakeholders and component owners affected by this change as reviewers

Configure `movement init` to Movement devnet and testnet, remove mainnet for now

---

Cargo.lock
Cargo.toml
crates/indexer/src/models/move_tables.rs
ecosystem/indexer-grpc/indexer-grpc-fullnode/src/convert.rs

Movement Tx doesn't have WriteSet data. Aptos indexer Grpc notification, suppose they're always set for broadcast Tx.
Remove unwrap and panic for Tx writeset processing to allow Tx without WriteSet to be notified.
Change the `aptos-indexer-processors` to Movement one.
I test locally with a Suzuka node.

Indexer: Remove all unwrap and panic for missing Tx WriteSet data.

---

ecosystem/indexer-grpc/indexer-grpc-fullnode/src/convert.rs

Remove the panic in the WriteSet change conversion for the indexer grpc stream. 
- [] Other (specify)
Run the indexer test with movement branch.

Remove panic in write_set_change grpc convertion

---

.movement/config.yaml
crates/aptos/src/common/init.rs

@Rahat-ch mentioned devs complaining about broken `movement init` process with testnet, that the lack of faucet access was making it so the Movement config file couldn't be created.
In this fix, `movement init` on testnet
- without `--skip-faucet` returns an error message recommending to use the flag in order to generate the Movement config.
- with `--skip-faucet` returns a success message linking users to the faucet UI.
- Tested locally with CLI
- All changes are in `crates/aptos/src/common/init.rs`

Fix: Recommend --skip-faucet flag on movement init with testnet and link to faucet after creating profile

---

crates/aptos/src/common/init.rs

We were returning `            return Err(
"For testnet, start over and run movement init --skip-faucet");`
which compiled locally for me, but I noticed it caused CI to fail [this job](https://github.com/movementlabsxyz/movement/pull/506) with error
```
Compiling aptos-node v0.0.0-main (/home/runner/actions-runner/_work/movement/movement/aptos-core/aptos-node)
error[E0308]: mismatched types
--> crates/aptos/src/common/init.rs:130:24
|
130 |             return Err("For testnet, start over and run movement init --skip-faucet");
|                    --- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `CliError`, found `&str`
|                    |
|                    arguments to this enum variant are incorrect
|
help: the type constructed contains `&'static str` due …
```

Fix error return format in init.rs

---

types/src/state_store/state_key/registry.rs

When removing entries from the `StateKey` registry,
defer drop to after the lock is released. This should prevent deadlocks seen in https://github.com/movementlabsxyz/movement/pull/576

Break lock reentrancy in StateKey registry

---

Cargo.lock
storage/aptosdb/Cargo.toml
storage/aptosdb/src/pruner/pruner_worker.rs
storage/aptosdb/src/pruner/state_merkle_pruner/mod.rs
storage/aptosdb/src/pruner/state_merkle_pruner/state_merkle_shard_pruner.rs

As we use tracing in Movement and aptos-logger does not integrate with that (rather, it wants to redirect the global tracing subscriber), selectively switch the few log event macros we are currently interested in observing to be emitted with tracing.
Will observe logs in an integration branch in movement.

Patch log macros in db pruner to use tracing

---

aptos-move/framework/aptos-framework/sources/atomic_bridge.move

- Add `get_bridge_transfers_initiator` and `get_bridge_transfers_counterparty` view functions into `atomic_bridge_store` module with corresponding Move unit tests. All tests pass with `movement move test`
- Fix a bug where `create_time_lock` was called twice, resulting in time locks farther into the future than expected.
- [ x] New feature
- [ x] Bug fix
- [ x] Tests
- [x ] Aptos Framework
In `aptos-move/framework/aptos-framework/sources` run `movement move test` or `aptos move test`.
I think this works better as two separate functions because of the way it aligns with the `BridgeContract` trait in our Rust code. However, it could be possible to combine them into one function if someone wants to do that. For now this seems like a good solution to being able to fetch details without …

Atomic Bridge: Add `get_bridge_transfer_details` view function and fix duplicate `create_time_lock` calls

---

Cargo.lock
Cargo.toml
crates/aptos/Cargo.toml
crates/aptos/src/node/local_testnet/processors.rs

A step to fixing https://github.com/movementlabsxyz/movement/security/dependabot/12
Requires https://github.com/movementlabsxyz/aptos-indexer-processors/pull/5
Bump diesel to 2.2 and diesel-async to 0.5 
CI tests should pass
This pulls in a newer revision of aptos-indexer-processors, which required adaptation in local_testnet CLI.

Dependency bump for diesel 2.2 and diesel-async 0.5

---

.gitignore
aptos-move/e2e-move-tests/src/tests/bridge.rs
aptos-move/framework/aptos-framework/doc/atomic_bridge.md
aptos-move/framework/aptos-framework/doc/genesis.md
aptos-move/framework/aptos-framework/sources/atomic_bridge.move
aptos-move/framework/aptos-framework/sources/genesis.move

- Because `initiateBridgeTransfer` will already have been successfully called on the Eth initiator side, there is no need to check EIP-55 compliance in `atomic_bridge_counterparty::lock_bridge_transfer_assets`. 
- The bridge team has decided for event listening it would make sense to use event handles rather than module events for this iteration of the bridge.
- This PR adds an optional function `ethereum_address_no_eip55` containing a check `assert_40_char_hex` to check that the address is a nonzero 40-character hex string.
- Move unit tests: `aptos move test` passes for all tests in `aptos-move/framework/aptos-framework/sources`
- E2E Move tests: Navigate to `aptos-move/e2e-move-tests` and run `cargo test bridge`.
- Move prover (`aptos move prove`) results in success.
Note: I don't …

Remove EIP 55 check from `atomic_bridge_counterparty::lock_bridge_transfer_assets` and use `EventHandle` for events 

---

aptos-move/e2e-move-tests/src/tests/bridge.rs
aptos-move/framework/aptos-framework/doc/atomic_bridge.md
aptos-move/framework/aptos-framework/doc/native_bridge.md
aptos-move/framework/aptos-framework/sources/atomic_bridge.move
aptos-move/framework/aptos-framework/sources/native_bridge.move
aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs

See [Issue 905](https://github.com/movementlabsxyz/movement/issues/905). Param serialization on the Move side needs to be done the same way as on the Solidity side so the bridge transfer IDs will be equal. 
- [ x] New feature
- [ x] Bug fix
- [ x] Performance improvement
- [ x] Tests
- Move unit tests: In `aptos-move/framework/aptos-framework` run `movement move test`
- E2E Move tests: In `aptos-move/e2e-move-tests` run `cargo test bridge -- --nocapture`
- I currently have left the debugging in to help reviewers see that the expected bridge transfer IDs are being calculated. Once reviewers are satisfied that this approach is correct, I'll remove the debugging. It was a bit of a mental workout getting this all working so I wanted to leave in a trail of breadcrumbs for the benefit of …

Native bridge: Modify param serialization to make bridge transfer IDs match on Move and Solidity sides in both L1 -> L2 and L2 -> L1 directions

---

aptos-move/framework/aptos-framework/sources/governed_gas_pool.move
aptos-move/framework/aptos-framework/sources/governed_gas_pool.spec.move
aptos-move/framework/aptos-framework/sources/transaction_validation.move

Fixed visibility of `deposit_gas_fee` by asserting caller is framework signer. 
Note that `(friend)` modifier fix did not work here because, this means that transaction validation module, which calls `deposit_gas_fee` must be a friend of ggp. Doing so creates a circular dependency cycle between transaction validation module and the ggp module. 
So instead, we just check that the signer of a `deposit_gas_fee` call is the framework signer and abort if not.
🟢 `movement move build`
🟢 `movement move test`

GGP feat: assert framework signer for deposit from 

---

aptos-move/framework/aptos-framework/doc/governed_gas_pool.md
aptos-move/framework/aptos-framework/doc/native_bridge.md
aptos-move/framework/aptos-framework/sources/governed_gas_pool.move
aptos-move/framework/aptos-framework/sources/governed_gas_pool.spec.move

- Clean up various Move warnings in `governed_gas_pool.move` and `governed_gas_pool.spec.move`
- [ x] Tests
- [ x] Aptos Framework
`movement move test`
- [x ] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [ x] I have performed a self-review of my own code
- [ x] I identified and added all stakeholders and component owners affected by this change as reviewers
- [ x] I have made corresponding changes to the documentation
In `aptos-move/e2e-move-tests`, `cargo test` fails with an unrelated error that also appears in the Aptos Labs `aptos-core` repo. Issue opened here: https://github.com/movementlabsxyz/aptos-core/issues/130

Cleanup Move warnings in Governed Gas Pool module and spec

---

aptos-move/framework/aptos-framework/doc/chain_status.md
aptos-move/framework/aptos-framework/sources/transaction_fee.move
aptos-move/framework/move-stdlib/doc/features.md

Adds mint_to and burn_from functions
Currently untested. Requires movementlabsxyz/movement verification, using scripts and core_resource_account minting and burning

Add mint_to and burn_from functions in tx_fees module

---

aptos-move/framework/aptos-framework/sources/primary_fungible_store.move

- Issue #148 
- Call `account::create_account_if_does_not_exist` in `primary_fungible_store::transfer` to avoid funds being stuck in new accounts.
- Move unit tests all still pass.
- [ x] Bug fix
- [ x] Performance improvement
- [ x] Aptos Framework
- `aptos move test`
- This should be a pretty trivial change with no unwanted side effects, as it simply creates an account if one doesn't exist for the recipient.
- [ x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I identified and added all stakeholders and component owners affected by this change as reviewers

fix: on `primary_fungible_store::transfer` create account if needed
